<!DOCTYPE html>
<html>
    <head>
        <title>VUT game</title>
        <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
        <link href="assets/layout.css" rel="stylesheet" media="screen">
        <link rel="shortcut icon" href="../Obrazky/vut.jpg" type="image/x-icon">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

    </head>
    <body>