<!DOCTYPE html>
<html>
    <head>
        <title>VUT game</title>
        <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
        <link href="assets/layout.css" rel="stylesheet" media="screen">
        <script src="js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
        <link rel="shortcut icon" href="vut.jpg" type="image/x-icon">

    </head>
    <body>