<?php
include_once 'views/navMenu.phtml';
require_once 'models/database.php';
$conn = new Database();
?>
<div class="container">
    <div class="aktual">
        <div class="hero-unit">
            <h1>Aktuality</h1><br>
            <p>Verze <strong>1.0.1.</strong> - Totální základ, všechno funguje jen velmi jemně. Stále nefunguje Timer.</p>
            <br>
            <hr style="border-color: #0e0e0e">
            <p style="float: right;">Registrováno je již <?php echo $conn->tableRowsCount('tbl_users'); ?> uživatelů</p>
        </div>
    </div>
</div>