<?php

if(isset($this->msg) && count($this->msg) > 0)
{
    foreach($this->msg as $msgData)
    {
        $msgType = $msgData['type'];
        $msgText = $msgData['text'];
        if($msgType == 'ERROR')
        {
            echo("<div class='alert alert-error'><button class='close' data-dismiss='alert'>&times;</button>" . $msgText . "</div>");
        }
        else if($msgType == 'SUCCESS')
        {
            echo("<div class='alert alert-success'><button class='close' data-dismiss='alert'>&times;</button>" . $msgText . "</div>");
        }
    }
}
