<?php
/**
 * Created by PhpStorm.
 * User: lesnek
 * Date: 7.4.17
 * Time: 11:00
 */
require_once __DIR__.'/../models/user.php';
$user = new USER();
$user->load(base64_decode($_SESSION['userSession']));
?>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="../home.php">VUT game</a>
            <div class="nav-collapse collapse">
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a href="#" role="button" class="dropdown-toggle"
                           data-toggle="dropdown">lvl <?php echo$user->getLevl(); ?> <i class="icon-user"></i>
                            <?php echo $user->getUserName(); ?> <i class="caret"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a tabindex="-1" href="../logout.php">Odhlásit</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav">
                    <li>
                        <a href="../postava.php">Postava</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Výzvy<b class="caret"></b>

                        </a>
                        <ul class="dropdown-menu" id="menu1">
                            <li><a href="../prednaska.php">Přednáška</a></li>
                            <li><a href="../cviko.php">Cvičení</a></li>
                            <li><a href="../zapocet.php">Zápočet</a></li>
                            <li><a href="../zkouska.php">Zkouška</a></li>
                            <li><a href="../diplomka.php">Diplomka</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="../uceni.php">Učení</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>