<?php
    $level      = $user->getLevl();
    $zkusenosti = $user->getZkusenosti();
    $levelC     = new levels();
    $endExp     = $levelC->getEndExp($level)-$levelC->getStartExp($level);
    $startExp   = $zkusenosti-$levelC->getStartExp($level);
    $progress   = $levelC->levelProgress($user,$level,$zkusenosti);
?>
<div class="postava">
    <div class="container">
        <div class="sedma">
            <div class="logoVUT">
                <br>
                <h3><?php echo $user->getUserName(); ?> - Level <?php echo $level;;?></h3><br>
                Zkušenosti:
                <div class="progress">
                    <div class="bar bar-danger" role="progressbar" aria-valuenow="<?php echo $progress; ?>" aria-valuemin="0" aria-valuemax="100" style="width:<?php echo $progress; ?>%">
                        <?php echo ($startExp).'/'.($endExp); ?></div>
                </div>
                <?php
                if ($user->getPohlavi() == 'M')
                {
                    echo '<img src="Obrazky/kluk.png">';
                } else
                    {
                    echo '<img src="Obrazky/holka.png">';
                    }
                    ?>
            </div>
            <hr style="border-color: #0e0e0e">
            <table class="stats">
                <tr>
                    <td>
                        <?php echo $user->getEnergie(); ?>
                    </td>
                    <td style="text-align: right">
                        <img src="Obrazky/blesk.png">
                    </td>
                    <td style="text-align: left">
                        Energie
                    </td>
                    <td class="neaktiv">
                        <img src="Obrazky/plus.png">
                        <span class="aktiv">Enegie na testy, přednášky, cvičení a zkoušky.</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php echo $user->getStesti(); ?>
                    </td>
                    <td>
                        <img src="Obrazky/ctyrlistek.png">
                    </td>
                    <td>
                        Štěstí
                    </td>
                    <td class="neaktiv">
                        <img src="Obrazky/plus.png">
                        <span class="aktiv">Zvyšuje náhodnou šanci na úspěch.</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php echo $user->getInteligence(); ?>
                    </td>
                    <td>
                        <img src="Obrazky/mozek.png">
                    </td>
                    <td>
                        Inteligence
                    </td>
                    <td class="neaktiv">
                        <img src="Obrazky/plus.png">
                        <span class="aktiv">Zvyšuje šanci na úspěch.</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php echo $user->getSoustredeni(); ?>
                    </td>
                    <td>
                        <img src="Obrazky/zarovka.png">
                    </td>
                    <td>
                        Soustředění
                    </td>
                    <td class="neaktiv">
                        <img src="Obrazky/plus.png">
                        <span class="aktiv">Zvýší hodnotu inteligence při učení.</span>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>