<div class="container">
    <div class="aktual">
        <div class="hero-unit">
            <h1>Přednáška</h1>
            <div class="logoVUT"><img src="../Obrazky/ucitel.png"></div>
            <hr style="border-color: #0e0e0e">
            <p>Přednášky všichni známe, samozřejmě vaše postava, když jde na ni, tak jde na celé dvě hodiny! Níže si
                však musíte vybrat
                jak dlouho vaše postava dokáže ze dvou hodin dávat pozor a víme jak náročné to je na celé dvě
                hodiny!</p>
            <div class="row span6">
                <form method="post" action="prednaska.php">
                    <select name="prednaska" title="prednaska" style="margin-top: 10px">
                        <option value="" disabled selected>Vyberte jak dlouho vydržíte:</option>
                        <?php
                        foreach($this->userQuestList as $userQuest) {
                            /** @var UserQuest $userQuest */
                            $questId = $userQuest->getTaskId();
                            $status = $userQuest->getStatus();
                            $statusText = ' / mozno zahajit';
                            if($status == quest::STATUS_READY_TO_COLLECT) {
                                $statusText = ' / mozno vybrat';
                            } else if ($status == quest::STATUS_RUNNING){
                                $statusText = ' / stale bezi';
                            }

                            /** @var quest $quest */
                            $quest = $this->questList[$questId];
                            $optionText = $quest->getDesc() . $statusText;
                            $optionValue = $quest->getId();
                            echo('<option value="'.$optionValue.'">'.$optionText.'</option>');
                        }
                        ?>
                    </select>
                    <button id="button_submit_start"   style="display: none" class="btn btn-small btn-success" type="submit" name="zacit">Začít</button>
                    <button id="button_submit_collect" style="display: none" class="btn btn-small btn-success" type="submit" name="vybrat">Vybrat</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    var userQuest = <?php echo(quests::userQuestListToJson($this->userQuestList)); ?>;

</script>
