<div id="login">
        <?php include_once "message.phtml"; ?>
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">Registrace</h2><hr />
            <input type="text" class="input-block-level" placeholder="Login" name="txtuname" required>
            <input type="email" class="input-block-level" placeholder="Email" name="txtemail" required>
            <input type="password" class="input-block-level" placeholder="Heslo" name="txtpass" required>
            <label>
                <input type="radio" class="radio-inline" name="pohlavi" value="M" required> Muž
                <input type="radio" class="radio-inline" name="pohlavi" value="W" required> Žena
            </label>
            <hr />
            <button class="btn btn-large btn-primary" type="submit" name="btn-signup">Registrovat</button>
        </form>
</div>
